### PR TITLE
Added mention of Arachni in DAST

### PR DESCRIPTION
**Pull request by Zapotek**
[Arachni](https://www.arachni-scanner.com/) is a F/OSS web application security scanner, albeit with a [proprietary license](https://github.com/Arachni/arachni/blob/master/LICENSE.md).
However, I do think it fits the bill.

GH: https://github.com/Arachni/arachni

### CODE REVIEW

**Comment by shkpk** [comment]
Arachni is heading towards obsolescence, try out its next-gen successor [Ecsypno](https://ecsypno.com/) [SCNR](https://ecsypno.com/scnr-documentation/)!

**Comment by Zapotek** [comment]
Yes but it'll be a year or so or more, I'm just guessing here, it's up to the users.
And that doesn't stop anyone from using it anyways. :)

**Comment by Zapotek** [comment]
@sottlmarek TLDR; I had announced that some time ago but I revived the project.

I see where you're coming from but actually maintenance has continued and will continue until migration to SCNR completes, but like I said, that would depend on the users.

Regardless, do what you think best of course.

**Comment by sottlmarek** [comment]
Will reopen this PR after the activity or migration of Arachni will be completed /renewed. Still great tool !

**Pull request closed without merging**
