### PR TITLE
OSS and Dependecy management - Add Renovatebot

### PR DESCRIPTION
**Pull request by philippe-granet**

### CODE REVIEW

**Comment by sottlmarek** [comment]
Hi Philipe, can you elaborate how Renovatebot is related to cyber security in DevOps? 

Thank you. Looking forward for your answer.

**Comment by philippe-granet** [comment]
It's a tool similar to Dependabot, and addresses an important issue in software development projects: keeping dependencies up to date.  
Updating dependencies closes potential security vulnerabilities and allows us to use recent features and apply bug fixes.

From renovatebot doc:

> Why Use Renovate?
> Receive automated Pull Requests whenever dependencies need updating
> Define schedules to avoid unnecessary noise in projects (e.g. for weekends or outside of working hours, or weekly updates, etc.)
> Relevant package files are discovered automatically (e.g. supports monorepo architecture such as Lerna or Yarn workspaces without further configuration)
> Bot behavior is extremely customizable via configuration files (config as code)
> Use ESLint-like shared config presets for ease of use and simplifying configuration (JSON format only)
> Lock files are natively supported and updated in the same commit, including immediately resolving conflicts whenever PRs are merged
> Supports GitHub (.com and Enterprise), GitLab (.com and CE/EE), Bitbucket Cloud, Bitbucket Server, Azure DevOps and Gitea.
> Open source (installable via npm/Yarn or Docker Hub) so can be self-hosted or used via GitHub App

**Comment by groves33** [comment]
gh pr checkout 8

**Comment by sottlmarek** [comment]
I did research this is little bit edgy because dependency updates can introduce new vulnerabilities and Renovatebot doesn't allow to scan the vulnerabilities and recommend patches. Which Dependabot to some extend, can do and provides security results. 

I can add the tool, but don't want to launch the wave of DevOps tools being committed and not the DevSecOps specific tools.

**Comment by philippe-granet** [comment]
@sottlmarek 
Renovate can read from GitHub's Vulnerability Alerts and customize Pull Requests accordingly.  
For this to work, you must first ensure you have enabled "Dependency graph" and "Dependabot alerts" under the "Security & analysis" section of the Github repository's "Settings" tab.

https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts

**Comment by sottlmarek** [comment]
Thanks for great resource! Already merged to master.

**Pull request merged**
